export const tempModule = {
	state: {
		days: {
			'2024-11-25': [
				{
					id: 1,
					task: 'школа',
					start: '8:00',
					end: '14:15',
					repeat: 'monday',
					comment: 'контрольная по математике',
				},
				{
					id: 2,
					task: 'обед',
					start: '14:30',
					end: '15:00',
					repeat: 'monday',
					comment: 'домашняя еда',
				},
				{
					id: 3,
					task: 'танцы',
					start: '16:00',
					end: '17:30',
					repeat: 'monday',
					comment: 'групповое занятие',
				},
				{
					id: 4,
					task: 'репетитор',
					start: '18:00',
					end: '19:30',
					repeat: 'monday',
					comment: 'подготовка к экзаменам',
				},
				{
					id: 29,
					task: 'йога',
					start: '19:00',
					end: '21:00',
					repeat: 'monday',
					comment: 'вечерняя практика',
				},
				{
					id: 248,
					task: 'чай',
					start: '19:15',
					end: '19:30',
					repeat: 'monday',
					comment: 'вечерняя практика',
				},
				{
					id: 30,
					task: 'чтение',
					start: '20:30',
					end: '21:30',
					repeat: 'monday',
					comment: 'книга по истории',
				}
			],
			'2024-11-26': [
				{
					id: 5,
					task: 'английский',
					start: '9:00',
					end: '10:30',
					repeat: 'tuesday',
					comment: 'разговорная практика',
				},
				{
					id: 6,
					task: 'врач',
					start: '11:00',
					end: '12:00',
					repeat: 'tuesday',
					comment: 'плановый осмотр',
				},
				{
					id: 7,
					task: 'бассейн',
					start: '16:00',
					end: '17:30',
					repeat: 'tuesday',
					comment: 'тренировка',
				},
				{
					id: 8,
					task: 'рисование',
					start: '18:00',
					end: '19:30',
					repeat: 'tuesday',
					comment: 'художественная школа',
				}
			],
			'2024-11-27': [
				{
					id: 9,
					task: 'школа',
					start: '8:00',
					end: '14:15',
					repeat: 'wednesday',
					comment: 'презентация проекта',
				},
				{
					id: 10,
					task: 'музыка',
					start: '15:00',
					end: '16:30',
					repeat: 'wednesday',
					comment: 'урок фортепиано',
				},
				{
					id: 11,
					task: 'психолог',
					start: '17:00',
					end: '18:00',
					repeat: 'wednesday',
					comment: 'консультация',
				},
				{
					id: 12,
					task: 'йога',
					start: '19:00',
					end: '20:00',
					repeat: 'wednesday',
					comment: 'групповое занятие',
				}
			],
			'2024-11-28': [
				{
					id: 13,
					task: 'стоматолог',
					start: '10:00',
					end: '11:00',
					repeat: 'thursday',
					comment: 'профилактический осмотр',
				},
				{
					id: 14,
					task: 'обед с друзьями',
					start: '12:00',
					end: '13:30',
					repeat: 'thursday',
					comment: 'пиццерия',
				},
				{
					id: 15,
					task: 'теннис',
					start: '15:00',
					end: '16:30',
					repeat: 'thursday',
					comment: 'индивидуальная тренировка',
				},
				{
					id: 16,
					task: 'программирование',
					start: '17:00',
					end: '18:30',
					repeat: 'thursday',
					comment: 'курсы Python',
				}
			],
			'2024-11-29': [
				{
					id: 17,
					task: 'школа',
					start: '8:00',
					end: '14:15',
					repeat: 'friday',
					comment: 'олимпиада по физике',
				},
				{
					id: 18,
					task: 'шопинг',
					start: '15:00',
					end: '17:00',
					repeat: 'friday',
					comment: 'покупка одежды',
				},
				{
					id: 19,
					task: 'кино',
					start: '18:00',
					end: '20:00',
					repeat: 'friday',
					comment: 'премьера фильма',
				},
				{
					id: 20,
					task: 'ужин с семьей',
					start: '20:30',
					end: '22:00',
					repeat: 'friday',
					comment: 'ресторан',
				}
			],
			'2024-11-30': [
				{
					id: 21,
					task: 'шахматы',
					start: '10:00',
					end: '11:30',
					repeat: 'saturday',
					comment: 'турнир',
				},
				{
					id: 22,
					task: 'встреча с друзьями',
					start: '12:00',
					end: '14:00',
					repeat: 'saturday',
					comment: 'боулинг',
				},
				{
					id: 23,
					task: 'фотосессия',
					start: '15:00',
					end: '16:30',
					repeat: 'saturday',
					comment: 'семейная съемка',
				},
				{
					id: 24,
					task: 'концерт',
					start: '19:00',
					end: '21:00',
					repeat: 'saturday',
					comment: 'филармония',
				}
			],
			'2024-12-01': [
				{
					id: 25,
					task: 'завтрак с друзьями',
					start: '10:00',
					end: '11:30',
					repeat: 'sunday',
					comment: 'кафе',
				},
				{
					id: 26,
					task: 'прогулка',
					start: '12:00',
					end: '14:00',
					repeat: 'sunday',
					comment: 'парк',
				},
				{
					id: 27,
					task: 'spa',
					start: '15:00',
					end: '17:00',
					repeat: 'sunday',
					comment: 'массаж и бассейн',
				},
				{
					id: 28,
					task: 'подготовка к неделе',
					start: '18:00',
					end: '19:00',
					repeat: 'sunday',
					comment: 'планирование',
				}
			]
		}
	},
	namespaced: true,
}
